// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: asset_categories.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const categoryNameExists = `-- name: CategoryNameExists :one

SELECT EXISTS (
    SELECT 1 FROM asset_categories WHERE lower(name) = lower($1)
)
`

// ─── Existence checks ────────────────────────────────────────────────────────
func (q *Queries) CategoryNameExists(ctx context.Context, name string) (bool, error) {
	row := q.db.QueryRow(ctx, categoryNameExists, name)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const categoryNameExistsExcludingID = `-- name: CategoryNameExistsExcludingID :one
SELECT EXISTS (
    SELECT 1
    FROM   asset_categories
    WHERE  lower(name) = lower($1)
    AND    asset_categories.id <> $2
)
`

type CategoryNameExistsExcludingIDParams struct {
	Name string      `json:"name"`
	ID   pgtype.UUID `json:"id"`
}

func (q *Queries) CategoryNameExistsExcludingID(ctx context.Context, arg CategoryNameExistsExcludingIDParams) (bool, error) {
	row := q.db.QueryRow(ctx, categoryNameExistsExcludingID, arg.Name, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createCategory = `-- name: CreateCategory :one

INSERT INTO asset_categories (
    name,
    description,
    dynamic_schema,
    status
) VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, name, description, dynamic_schema, status, created_at, updated_at
`

type CreateCategoryParams struct {
	Name          string              `json:"name"`
	Description   *string             `json:"description"`
	DynamicSchema []byte              `json:"dynamic_schema"`
	Status        AssetCategoryStatus `json:"status"`
}

// ─── Create ───────────────────────────────────────────────────────────────────
func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (AssetCategory, error) {
	row := q.db.QueryRow(ctx, createCategory,
		arg.Name,
		arg.Description,
		arg.DynamicSchema,
		arg.Status,
	)
	var i AssetCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.DynamicSchema,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCategoryByID = `-- name: GetCategoryByID :one

SELECT id, name, description, dynamic_schema, status, created_at, updated_at
FROM   asset_categories
WHERE  asset_categories.id = $1
`

// ─── Read ─────────────────────────────────────────────────────────────────────
func (q *Queries) GetCategoryByID(ctx context.Context, id pgtype.UUID) (AssetCategory, error) {
	row := q.db.QueryRow(ctx, getCategoryByID, id)
	var i AssetCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.DynamicSchema,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT id, name, description, dynamic_schema, status, created_at, updated_at
FROM   asset_categories
ORDER BY name ASC
`

func (q *Queries) ListCategories(ctx context.Context) ([]AssetCategory, error) {
	rows, err := q.db.Query(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AssetCategory{}
	for rows.Next() {
		var i AssetCategory
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.DynamicSchema,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoriesByStatus = `-- name: ListCategoriesByStatus :many
SELECT id, name, description, dynamic_schema, status, created_at, updated_at
FROM   asset_categories
WHERE  status = $1
ORDER BY name ASC
`

func (q *Queries) ListCategoriesByStatus(ctx context.Context, status AssetCategoryStatus) ([]AssetCategory, error) {
	rows, err := q.db.Query(ctx, listCategoriesByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AssetCategory{}
	for rows.Next() {
		var i AssetCategory
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.DynamicSchema,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :one

UPDATE asset_categories
SET
    name           = $1,
    description    = $2,
    dynamic_schema = $3
WHERE asset_categories.id = $4
RETURNING id, name, description, dynamic_schema, status, created_at, updated_at
`

type UpdateCategoryParams struct {
	Name          string      `json:"name"`
	Description   *string     `json:"description"`
	DynamicSchema []byte      `json:"dynamic_schema"`
	ID            pgtype.UUID `json:"id"`
}

// ─── Update ───────────────────────────────────────────────────────────────────
func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (AssetCategory, error) {
	row := q.db.QueryRow(ctx, updateCategory,
		arg.Name,
		arg.Description,
		arg.DynamicSchema,
		arg.ID,
	)
	var i AssetCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.DynamicSchema,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCategoryStatus = `-- name: UpdateCategoryStatus :one
UPDATE asset_categories
SET status = $1
WHERE asset_categories.id = $2
RETURNING id, name, description, dynamic_schema, status, created_at, updated_at
`

type UpdateCategoryStatusParams struct {
	Status AssetCategoryStatus `json:"status"`
	ID     pgtype.UUID         `json:"id"`
}

func (q *Queries) UpdateCategoryStatus(ctx context.Context, arg UpdateCategoryStatusParams) (AssetCategory, error) {
	row := q.db.QueryRow(ctx, updateCategoryStatus, arg.Status, arg.ID)
	var i AssetCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.DynamicSchema,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
