// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: departments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDepartment = `-- name: CreateDepartment :one

WITH inserted AS (
    INSERT INTO departments (name, code, parent_id)
    VALUES ($1, $2, $3)
    RETURNING id, name, code, parent_id, status, created_at, updated_at
)
SELECT
    i.id,
    i.name,
    i.code,
    i.parent_id,
    i.status,
    i.created_at,
    i.updated_at,
    parent.name AS parent_name
FROM inserted i
LEFT JOIN departments parent ON parent.id = i.parent_id
`

type CreateDepartmentParams struct {
	Name     string      `json:"name"`
	Code     string      `json:"code"`
	ParentID pgtype.UUID `json:"parent_id"`
}

type CreateDepartmentRow struct {
	ID         pgtype.UUID        `json:"id"`
	Name       string             `json:"name"`
	Code       string             `json:"code"`
	ParentID   pgtype.UUID        `json:"parent_id"`
	Status     DepartmentStatus   `json:"status"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	ParentName *string            `json:"parent_name"`
}

// ─── Create ───────────────────────────────────────────────────────────────────
func (q *Queries) CreateDepartment(ctx context.Context, arg CreateDepartmentParams) (CreateDepartmentRow, error) {
	row := q.db.QueryRow(ctx, createDepartment, arg.Name, arg.Code, arg.ParentID)
	var i CreateDepartmentRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.ParentID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ParentName,
	)
	return i, err
}

const departmentCodeExists = `-- name: DepartmentCodeExists :one
SELECT EXISTS (
    SELECT 1 FROM departments WHERE upper(code) = upper($1)
)
`

func (q *Queries) DepartmentCodeExists(ctx context.Context, code interface{}) (bool, error) {
	row := q.db.QueryRow(ctx, departmentCodeExists, code)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const departmentCodeExistsExcludingID = `-- name: DepartmentCodeExistsExcludingID :one
SELECT EXISTS (
    SELECT 1
    FROM   departments
    WHERE  upper(code) = upper($1)
    AND    departments.id <> $2
)
`

type DepartmentCodeExistsExcludingIDParams struct {
	Code interface{} `json:"code"`
	ID   pgtype.UUID `json:"id"`
}

func (q *Queries) DepartmentCodeExistsExcludingID(ctx context.Context, arg DepartmentCodeExistsExcludingIDParams) (bool, error) {
	row := q.db.QueryRow(ctx, departmentCodeExistsExcludingID, arg.Code, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const departmentNameExists = `-- name: DepartmentNameExists :one

SELECT EXISTS (
    SELECT 1 FROM departments WHERE lower(name) = lower($1)
)
`

// ─── Existence checks (used by service layer for conflict validation) ──────────
func (q *Queries) DepartmentNameExists(ctx context.Context, name string) (bool, error) {
	row := q.db.QueryRow(ctx, departmentNameExists, name)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const departmentNameExistsExcludingID = `-- name: DepartmentNameExistsExcludingID :one
SELECT EXISTS (
    SELECT 1
    FROM   departments
    WHERE  lower(name) = lower($1)
    AND    departments.id <> $2
)
`

type DepartmentNameExistsExcludingIDParams struct {
	Name string      `json:"name"`
	ID   pgtype.UUID `json:"id"`
}

func (q *Queries) DepartmentNameExistsExcludingID(ctx context.Context, arg DepartmentNameExistsExcludingIDParams) (bool, error) {
	row := q.db.QueryRow(ctx, departmentNameExistsExcludingID, arg.Name, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getDepartmentByID = `-- name: GetDepartmentByID :one

SELECT
    d.id,
    d.name,
    d.code,
    d.parent_id,
    d.status,
    d.created_at,
    d.updated_at,
    parent.name AS parent_name
FROM departments d
LEFT JOIN departments parent ON parent.id = d.parent_id
WHERE d.id = $1
`

type GetDepartmentByIDRow struct {
	ID         pgtype.UUID        `json:"id"`
	Name       string             `json:"name"`
	Code       string             `json:"code"`
	ParentID   pgtype.UUID        `json:"parent_id"`
	Status     DepartmentStatus   `json:"status"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	ParentName *string            `json:"parent_name"`
}

// ─── Read ─────────────────────────────────────────────────────────────────────
func (q *Queries) GetDepartmentByID(ctx context.Context, id pgtype.UUID) (GetDepartmentByIDRow, error) {
	row := q.db.QueryRow(ctx, getDepartmentByID, id)
	var i GetDepartmentByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.ParentID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ParentName,
	)
	return i, err
}

const listDepartments = `-- name: ListDepartments :many
SELECT
    d.id,
    d.name,
    d.code,
    d.parent_id,
    d.status,
    d.created_at,
    d.updated_at,
    parent.name AS parent_name
FROM departments d
LEFT JOIN departments parent ON parent.id = d.parent_id
ORDER BY d.name ASC, d.id ASC
`

type ListDepartmentsRow struct {
	ID         pgtype.UUID        `json:"id"`
	Name       string             `json:"name"`
	Code       string             `json:"code"`
	ParentID   pgtype.UUID        `json:"parent_id"`
	Status     DepartmentStatus   `json:"status"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	ParentName *string            `json:"parent_name"`
}

func (q *Queries) ListDepartments(ctx context.Context) ([]ListDepartmentsRow, error) {
	rows, err := q.db.Query(ctx, listDepartments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDepartmentsRow{}
	for rows.Next() {
		var i ListDepartmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.ParentID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ParentName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDepartmentsByStatus = `-- name: ListDepartmentsByStatus :many
SELECT
    d.id,
    d.name,
    d.code,
    d.parent_id,
    d.status,
    d.created_at,
    d.updated_at,
    parent.name AS parent_name
FROM departments d
LEFT JOIN departments parent ON parent.id = d.parent_id
WHERE d.status = $1
ORDER BY d.name ASC, d.id ASC
`

type ListDepartmentsByStatusRow struct {
	ID         pgtype.UUID        `json:"id"`
	Name       string             `json:"name"`
	Code       string             `json:"code"`
	ParentID   pgtype.UUID        `json:"parent_id"`
	Status     DepartmentStatus   `json:"status"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	ParentName *string            `json:"parent_name"`
}

func (q *Queries) ListDepartmentsByStatus(ctx context.Context, status DepartmentStatus) ([]ListDepartmentsByStatusRow, error) {
	rows, err := q.db.Query(ctx, listDepartmentsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDepartmentsByStatusRow{}
	for rows.Next() {
		var i ListDepartmentsByStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.ParentID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ParentName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const parentDepartmentExists = `-- name: ParentDepartmentExists :one
SELECT EXISTS (
    SELECT 1 FROM departments WHERE departments.id = $1
)
`

func (q *Queries) ParentDepartmentExists(ctx context.Context, parentID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, parentDepartmentExists, parentID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateDepartment = `-- name: UpdateDepartment :one

WITH updated AS (
    UPDATE departments
    SET
        name      = $1,
        code      = $2,
        parent_id = $3
    WHERE departments.id = $4
    RETURNING id, name, code, parent_id, status, created_at, updated_at
)
SELECT
    u.id,
    u.name,
    u.code,
    u.parent_id,
    u.status,
    u.created_at,
    u.updated_at,
    parent.name AS parent_name
FROM updated u
LEFT JOIN departments parent ON parent.id = u.parent_id
`

type UpdateDepartmentParams struct {
	Name     string      `json:"name"`
	Code     string      `json:"code"`
	ParentID pgtype.UUID `json:"parent_id"`
	ID       pgtype.UUID `json:"id"`
}

type UpdateDepartmentRow struct {
	ID         pgtype.UUID        `json:"id"`
	Name       string             `json:"name"`
	Code       string             `json:"code"`
	ParentID   pgtype.UUID        `json:"parent_id"`
	Status     DepartmentStatus   `json:"status"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	ParentName *string            `json:"parent_name"`
}

// ─── Update ───────────────────────────────────────────────────────────────────
func (q *Queries) UpdateDepartment(ctx context.Context, arg UpdateDepartmentParams) (UpdateDepartmentRow, error) {
	row := q.db.QueryRow(ctx, updateDepartment,
		arg.Name,
		arg.Code,
		arg.ParentID,
		arg.ID,
	)
	var i UpdateDepartmentRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.ParentID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ParentName,
	)
	return i, err
}

const updateDepartmentStatus = `-- name: UpdateDepartmentStatus :one
WITH updated AS (
    UPDATE departments
    SET status = $1
    WHERE departments.id = $2
    RETURNING id, name, code, parent_id, status, created_at, updated_at
)
SELECT
    u.id,
    u.name,
    u.code,
    u.parent_id,
    u.status,
    u.created_at,
    u.updated_at,
    parent.name AS parent_name
FROM updated u
LEFT JOIN departments parent ON parent.id = u.parent_id
`

type UpdateDepartmentStatusParams struct {
	Status DepartmentStatus `json:"status"`
	ID     pgtype.UUID      `json:"id"`
}

type UpdateDepartmentStatusRow struct {
	ID         pgtype.UUID        `json:"id"`
	Name       string             `json:"name"`
	Code       string             `json:"code"`
	ParentID   pgtype.UUID        `json:"parent_id"`
	Status     DepartmentStatus   `json:"status"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	ParentName *string            `json:"parent_name"`
}

func (q *Queries) UpdateDepartmentStatus(ctx context.Context, arg UpdateDepartmentStatusParams) (UpdateDepartmentStatusRow, error) {
	row := q.db.QueryRow(ctx, updateDepartmentStatus, arg.Status, arg.ID)
	var i UpdateDepartmentStatusRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.ParentID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ParentName,
	)
	return i, err
}
