// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: employee.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countEmployees = `-- name: CountEmployees :one
SELECT COUNT(*) FROM employees
`

func (q *Queries) CountEmployees(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countEmployees)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEmployeesByStatus = `-- name: CountEmployeesByStatus :one
SELECT COUNT(*) FROM employees
WHERE status = $1
`

func (q *Queries) CountEmployeesByStatus(ctx context.Context, status EmployeeStatus) (int64, error) {
	row := q.db.QueryRow(ctx, countEmployeesByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEmployee = `-- name: CreateEmployee :one
INSERT INTO employees (
    first_name,
    last_name,
    email,
    phone,
    department_id,
    job_title,
    status,
    hire_date
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, first_name, last_name, email, phone, department_id, job_title, status, hire_date, created_at, updated_at
`

type CreateEmployeeParams struct {
	FirstName    string         `json:"first_name"`
	LastName     string         `json:"last_name"`
	Email        string         `json:"email"`
	Phone        *string        `json:"phone"`
	DepartmentID pgtype.UUID    `json:"department_id"`
	JobTitle     *string        `json:"job_title"`
	Status       EmployeeStatus `json:"status"`
	HireDate     pgtype.Date    `json:"hire_date"`
}

func (q *Queries) CreateEmployee(ctx context.Context, arg CreateEmployeeParams) (Employee, error) {
	row := q.db.QueryRow(ctx, createEmployee,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Phone,
		arg.DepartmentID,
		arg.JobTitle,
		arg.Status,
		arg.HireDate,
	)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.DepartmentID,
		&i.JobTitle,
		&i.Status,
		&i.HireDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEmployee = `-- name: DeleteEmployee :exec
DELETE FROM employees
WHERE id = $1
`

func (q *Queries) DeleteEmployee(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEmployee, id)
	return err
}

const getEmployeeByEmail = `-- name: GetEmployeeByEmail :one
SELECT id, first_name, last_name, email, phone, department_id, job_title, status, hire_date, created_at, updated_at FROM employees
WHERE email = $1
LIMIT 1
`

func (q *Queries) GetEmployeeByEmail(ctx context.Context, email string) (Employee, error) {
	row := q.db.QueryRow(ctx, getEmployeeByEmail, email)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.DepartmentID,
		&i.JobTitle,
		&i.Status,
		&i.HireDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEmployeeByID = `-- name: GetEmployeeByID :one
SELECT id, first_name, last_name, email, phone, department_id, job_title, status, hire_date, created_at, updated_at FROM employees
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetEmployeeByID(ctx context.Context, id uuid.UUID) (Employee, error) {
	row := q.db.QueryRow(ctx, getEmployeeByID, id)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.DepartmentID,
		&i.JobTitle,
		&i.Status,
		&i.HireDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEmployees = `-- name: ListEmployees :many
SELECT id, first_name, last_name, email, phone, department_id, job_title, status, hire_date, created_at, updated_at FROM employees
ORDER BY last_name ASC, first_name ASC
`

func (q *Queries) ListEmployees(ctx context.Context) ([]Employee, error) {
	rows, err := q.db.Query(ctx, listEmployees)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Employee{}
	for rows.Next() {
		var i Employee
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Phone,
			&i.DepartmentID,
			&i.JobTitle,
			&i.Status,
			&i.HireDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmployeesByDepartment = `-- name: ListEmployeesByDepartment :many
SELECT id, first_name, last_name, email, phone, department_id, job_title, status, hire_date, created_at, updated_at FROM employees
WHERE department_id = $1
ORDER BY last_name ASC, first_name ASC
`

func (q *Queries) ListEmployeesByDepartment(ctx context.Context, departmentID pgtype.UUID) ([]Employee, error) {
	rows, err := q.db.Query(ctx, listEmployeesByDepartment, departmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Employee{}
	for rows.Next() {
		var i Employee
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Phone,
			&i.DepartmentID,
			&i.JobTitle,
			&i.Status,
			&i.HireDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmployeesByStatus = `-- name: ListEmployeesByStatus :many
SELECT id, first_name, last_name, email, phone, department_id, job_title, status, hire_date, created_at, updated_at FROM employees
WHERE status = $1
ORDER BY last_name ASC, first_name ASC
`

func (q *Queries) ListEmployeesByStatus(ctx context.Context, status EmployeeStatus) ([]Employee, error) {
	rows, err := q.db.Query(ctx, listEmployeesByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Employee{}
	for rows.Next() {
		var i Employee
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Phone,
			&i.DepartmentID,
			&i.JobTitle,
			&i.Status,
			&i.HireDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEmployee = `-- name: UpdateEmployee :one
UPDATE employees SET
    first_name    = $2,
    last_name     = $3,
    email         = $4,
    phone         = $5,
    department_id = $6,
    job_title     = $7,
    status        = $8,
    hire_date     = $9,
    updated_at    = NOW()
WHERE id = $1
RETURNING id, first_name, last_name, email, phone, department_id, job_title, status, hire_date, created_at, updated_at
`

type UpdateEmployeeParams struct {
	ID           uuid.UUID      `json:"id"`
	FirstName    string         `json:"first_name"`
	LastName     string         `json:"last_name"`
	Email        string         `json:"email"`
	Phone        *string        `json:"phone"`
	DepartmentID pgtype.UUID    `json:"department_id"`
	JobTitle     *string        `json:"job_title"`
	Status       EmployeeStatus `json:"status"`
	HireDate     pgtype.Date    `json:"hire_date"`
}

func (q *Queries) UpdateEmployee(ctx context.Context, arg UpdateEmployeeParams) (Employee, error) {
	row := q.db.QueryRow(ctx, updateEmployee,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Phone,
		arg.DepartmentID,
		arg.JobTitle,
		arg.Status,
		arg.HireDate,
	)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.DepartmentID,
		&i.JobTitle,
		&i.Status,
		&i.HireDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateEmployeeStatus = `-- name: UpdateEmployeeStatus :one
UPDATE employees SET
    status     = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, first_name, last_name, email, phone, department_id, job_title, status, hire_date, created_at, updated_at
`

type UpdateEmployeeStatusParams struct {
	ID     uuid.UUID      `json:"id"`
	Status EmployeeStatus `json:"status"`
}

func (q *Queries) UpdateEmployeeStatus(ctx context.Context, arg UpdateEmployeeStatusParams) (Employee, error) {
	row := q.db.QueryRow(ctx, updateEmployeeStatus, arg.ID, arg.Status)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.DepartmentID,
		&i.JobTitle,
		&i.Status,
		&i.HireDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
