// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: employees.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignDepartment = `-- name: AssignDepartment :one
UPDATE employees
SET department_id = $1
WHERE employees.id = $2
RETURNING
    id, first_name, last_name, email, password_hash,
    department_id, role, status, created_at, updated_at
`

type AssignDepartmentParams struct {
	DepartmentID pgtype.UUID `json:"department_id"`
	ID           pgtype.UUID `json:"id"`
}

func (q *Queries) AssignDepartment(ctx context.Context, arg AssignDepartmentParams) (Employee, error) {
	row := q.db.QueryRow(ctx, assignDepartment, arg.DepartmentID, arg.ID)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PasswordHash,
		&i.DepartmentID,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countEmployees = `-- name: CountEmployees :one
SELECT COUNT(*) FROM employees
`

func (q *Queries) CountEmployees(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countEmployees)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEmployeesByStatus = `-- name: CountEmployeesByStatus :one
SELECT COUNT(*) FROM employees WHERE status = $1
`

func (q *Queries) CountEmployeesByStatus(ctx context.Context, status EmployeeStatus) (int64, error) {
	row := q.db.QueryRow(ctx, countEmployeesByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEmployee = `-- name: CreateEmployee :one

INSERT INTO employees (
    first_name,
    last_name,
    email,
    password_hash,
    department_id,
    role,
    status
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING
    id, first_name, last_name, email, password_hash,
    department_id, role, status, created_at, updated_at
`

type CreateEmployeeParams struct {
	FirstName    string         `json:"first_name"`
	LastName     string         `json:"last_name"`
	Email        string         `json:"email"`
	PasswordHash string         `json:"password_hash"`
	DepartmentID pgtype.UUID    `json:"department_id"`
	Role         EmployeeRole   `json:"role"`
	Status       EmployeeStatus `json:"status"`
}

// ─── Create ───────────────────────────────────────────────────────────────────
func (q *Queries) CreateEmployee(ctx context.Context, arg CreateEmployeeParams) (Employee, error) {
	row := q.db.QueryRow(ctx, createEmployee,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.PasswordHash,
		arg.DepartmentID,
		arg.Role,
		arg.Status,
	)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PasswordHash,
		&i.DepartmentID,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEmployee = `-- name: DeleteEmployee :exec

DELETE FROM employees
WHERE id = $1
`

// ─── Delete & Count ──────────────────────────────────────────────────────────
func (q *Queries) DeleteEmployee(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteEmployee, id)
	return err
}

const employeeEmailExists = `-- name: EmployeeEmailExists :one

SELECT EXISTS (
    SELECT 1 FROM employees WHERE lower(email) = lower($1)
)
`

// ─── Existence checks ────────────────────────────────────────────────────────
func (q *Queries) EmployeeEmailExists(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, employeeEmailExists, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const employeeEmailExistsExcludingID = `-- name: EmployeeEmailExistsExcludingID :one
SELECT EXISTS (
    SELECT 1
    FROM   employees
    WHERE  lower(email) = lower($1)
    AND    employees.id <> $2
)
`

type EmployeeEmailExistsExcludingIDParams struct {
	Email string      `json:"email"`
	ID    pgtype.UUID `json:"id"`
}

func (q *Queries) EmployeeEmailExistsExcludingID(ctx context.Context, arg EmployeeEmailExistsExcludingIDParams) (bool, error) {
	row := q.db.QueryRow(ctx, employeeEmailExistsExcludingID, arg.Email, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getDepartmentHead = `-- name: GetDepartmentHead :one
SELECT
    id, first_name, last_name, email, password_hash,
    department_id, role, status, created_at, updated_at
FROM employees
WHERE department_id = $1
  AND role = 'department_head'
  AND status = 'active'
LIMIT 1
`

// Returns the employee with role 'department_head' in the given department.
func (q *Queries) GetDepartmentHead(ctx context.Context, departmentID pgtype.UUID) (Employee, error) {
	row := q.db.QueryRow(ctx, getDepartmentHead, departmentID)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PasswordHash,
		&i.DepartmentID,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEmployeeByEmail = `-- name: GetEmployeeByEmail :one
SELECT
    id, first_name, last_name, email, password_hash,
    department_id, role, status, created_at, updated_at
FROM employees
WHERE email = $1
`

func (q *Queries) GetEmployeeByEmail(ctx context.Context, email string) (Employee, error) {
	row := q.db.QueryRow(ctx, getEmployeeByEmail, email)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PasswordHash,
		&i.DepartmentID,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEmployeeByID = `-- name: GetEmployeeByID :one

SELECT
    id, first_name, last_name, email, password_hash,
    department_id, role, status, created_at, updated_at
FROM employees
WHERE employees.id = $1
`

// ─── Read ─────────────────────────────────────────────────────────────────────
func (q *Queries) GetEmployeeByID(ctx context.Context, id pgtype.UUID) (Employee, error) {
	row := q.db.QueryRow(ctx, getEmployeeByID, id)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PasswordHash,
		&i.DepartmentID,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEmployees = `-- name: ListEmployees :many
SELECT
    id, first_name, last_name, email, password_hash,
    department_id, role, status, created_at, updated_at
FROM employees
ORDER BY last_name ASC, first_name ASC
`

func (q *Queries) ListEmployees(ctx context.Context) ([]Employee, error) {
	rows, err := q.db.Query(ctx, listEmployees)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Employee{}
	for rows.Next() {
		var i Employee
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.PasswordHash,
			&i.DepartmentID,
			&i.Role,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmployeesByDepartment = `-- name: ListEmployeesByDepartment :many
SELECT
    id, first_name, last_name, email, password_hash,
    department_id, role, status, created_at, updated_at
FROM employees
WHERE department_id = $1
ORDER BY last_name ASC, first_name ASC
`

func (q *Queries) ListEmployeesByDepartment(ctx context.Context, departmentID pgtype.UUID) ([]Employee, error) {
	rows, err := q.db.Query(ctx, listEmployeesByDepartment, departmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Employee{}
	for rows.Next() {
		var i Employee
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.PasswordHash,
			&i.DepartmentID,
			&i.Role,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmployeesByRole = `-- name: ListEmployeesByRole :many
SELECT
    id, first_name, last_name, email, password_hash,
    department_id, role, status, created_at, updated_at
FROM employees
WHERE role = $1
ORDER BY last_name ASC, first_name ASC
`

func (q *Queries) ListEmployeesByRole(ctx context.Context, role EmployeeRole) ([]Employee, error) {
	rows, err := q.db.Query(ctx, listEmployeesByRole, role)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Employee{}
	for rows.Next() {
		var i Employee
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.PasswordHash,
			&i.DepartmentID,
			&i.Role,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmployeesByStatus = `-- name: ListEmployeesByStatus :many
SELECT
    id, first_name, last_name, email, password_hash,
    department_id, role, status, created_at, updated_at
FROM employees
WHERE status = $1
ORDER BY last_name ASC, first_name ASC
`

func (q *Queries) ListEmployeesByStatus(ctx context.Context, status EmployeeStatus) ([]Employee, error) {
	rows, err := q.db.Query(ctx, listEmployeesByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Employee{}
	for rows.Next() {
		var i Employee
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.PasswordHash,
			&i.DepartmentID,
			&i.Role,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEmployee = `-- name: UpdateEmployee :one

UPDATE employees
SET
    first_name = $1,
    last_name  = $2,
    email      = $3
WHERE employees.id = $4
RETURNING
    id, first_name, last_name, email, password_hash,
    department_id, role, status, created_at, updated_at
`

type UpdateEmployeeParams struct {
	FirstName string      `json:"first_name"`
	LastName  string      `json:"last_name"`
	Email     string      `json:"email"`
	ID        pgtype.UUID `json:"id"`
}

// ─── Update ───────────────────────────────────────────────────────────────────
func (q *Queries) UpdateEmployee(ctx context.Context, arg UpdateEmployeeParams) (Employee, error) {
	row := q.db.QueryRow(ctx, updateEmployee,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.ID,
	)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PasswordHash,
		&i.DepartmentID,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateEmployeeRole = `-- name: UpdateEmployeeRole :one
UPDATE employees
SET role = $1
WHERE employees.id = $2
RETURNING
    id, first_name, last_name, email, password_hash,
    department_id, role, status, created_at, updated_at
`

type UpdateEmployeeRoleParams struct {
	Role EmployeeRole `json:"role"`
	ID   pgtype.UUID  `json:"id"`
}

func (q *Queries) UpdateEmployeeRole(ctx context.Context, arg UpdateEmployeeRoleParams) (Employee, error) {
	row := q.db.QueryRow(ctx, updateEmployeeRole, arg.Role, arg.ID)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PasswordHash,
		&i.DepartmentID,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateEmployeeStatus = `-- name: UpdateEmployeeStatus :one
UPDATE employees
SET status = $1
WHERE employees.id = $2
RETURNING
    id, first_name, last_name, email, password_hash,
    department_id, role, status, created_at, updated_at
`

type UpdateEmployeeStatusParams struct {
	Status EmployeeStatus `json:"status"`
	ID     pgtype.UUID    `json:"id"`
}

func (q *Queries) UpdateEmployeeStatus(ctx context.Context, arg UpdateEmployeeStatusParams) (Employee, error) {
	row := q.db.QueryRow(ctx, updateEmployeeStatus, arg.Status, arg.ID)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PasswordHash,
		&i.DepartmentID,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePasswordHash = `-- name: UpdatePasswordHash :exec
UPDATE employees
SET password_hash = $1
WHERE employees.id = $2
`

type UpdatePasswordHashParams struct {
	PasswordHash string      `json:"password_hash"`
	ID           pgtype.UUID `json:"id"`
}

func (q *Queries) UpdatePasswordHash(ctx context.Context, arg UpdatePasswordHashParams) error {
	_, err := q.db.Exec(ctx, updatePasswordHash, arg.PasswordHash, arg.ID)
	return err
}
