// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AssetCategoryStatus string

const (
	AssetCategoryStatusActive   AssetCategoryStatus = "active"
	AssetCategoryStatusInactive AssetCategoryStatus = "inactive"
)

func (e *AssetCategoryStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AssetCategoryStatus(s)
	case string:
		*e = AssetCategoryStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AssetCategoryStatus: %T", src)
	}
	return nil
}

type NullAssetCategoryStatus struct {
	AssetCategoryStatus AssetCategoryStatus `json:"asset_category_status"`
	Valid               bool                `json:"valid"` // Valid is true if AssetCategoryStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAssetCategoryStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AssetCategoryStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AssetCategoryStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAssetCategoryStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AssetCategoryStatus), nil
}

func (e AssetCategoryStatus) Valid() bool {
	switch e {
	case AssetCategoryStatusActive,
		AssetCategoryStatusInactive:
		return true
	}
	return false
}

type DepartmentStatus string

const (
	DepartmentStatusActive   DepartmentStatus = "active"
	DepartmentStatusInactive DepartmentStatus = "inactive"
)

func (e *DepartmentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DepartmentStatus(s)
	case string:
		*e = DepartmentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for DepartmentStatus: %T", src)
	}
	return nil
}

type NullDepartmentStatus struct {
	DepartmentStatus DepartmentStatus `json:"department_status"`
	Valid            bool             `json:"valid"` // Valid is true if DepartmentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDepartmentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.DepartmentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DepartmentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDepartmentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DepartmentStatus), nil
}

func (e DepartmentStatus) Valid() bool {
	switch e {
	case DepartmentStatusActive,
		DepartmentStatusInactive:
		return true
	}
	return false
}

type EmployeeRole string

const (
	EmployeeRoleAdmin          EmployeeRole = "admin"
	EmployeeRoleAssetManager   EmployeeRole = "asset_manager"
	EmployeeRoleDepartmentHead EmployeeRole = "department_head"
	EmployeeRoleEmployee       EmployeeRole = "employee"
)

func (e *EmployeeRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EmployeeRole(s)
	case string:
		*e = EmployeeRole(s)
	default:
		return fmt.Errorf("unsupported scan type for EmployeeRole: %T", src)
	}
	return nil
}

type NullEmployeeRole struct {
	EmployeeRole EmployeeRole `json:"employee_role"`
	Valid        bool         `json:"valid"` // Valid is true if EmployeeRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEmployeeRole) Scan(value interface{}) error {
	if value == nil {
		ns.EmployeeRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EmployeeRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEmployeeRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EmployeeRole), nil
}

func (e EmployeeRole) Valid() bool {
	switch e {
	case EmployeeRoleAdmin,
		EmployeeRoleAssetManager,
		EmployeeRoleDepartmentHead,
		EmployeeRoleEmployee:
		return true
	}
	return false
}

type EmployeeStatus string

const (
	EmployeeStatusActive   EmployeeStatus = "active"
	EmployeeStatusInactive EmployeeStatus = "inactive"
)

func (e *EmployeeStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EmployeeStatus(s)
	case string:
		*e = EmployeeStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for EmployeeStatus: %T", src)
	}
	return nil
}

type NullEmployeeStatus struct {
	EmployeeStatus EmployeeStatus `json:"employee_status"`
	Valid          bool           `json:"valid"` // Valid is true if EmployeeStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEmployeeStatus) Scan(value interface{}) error {
	if value == nil {
		ns.EmployeeStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EmployeeStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEmployeeStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EmployeeStatus), nil
}

func (e EmployeeStatus) Valid() bool {
	switch e {
	case EmployeeStatusActive,
		EmployeeStatusInactive:
		return true
	}
	return false
}

type AssetCategory struct {
	ID            pgtype.UUID         `json:"id"`
	Name          string              `json:"name"`
	Description   *string             `json:"description"`
	DynamicSchema []byte              `json:"dynamic_schema"`
	Status        AssetCategoryStatus `json:"status"`
	CreatedAt     pgtype.Timestamptz  `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz  `json:"updated_at"`
}

type Department struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Code      string             `json:"code"`
	ParentID  pgtype.UUID        `json:"parent_id"`
	Status    DepartmentStatus   `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Employee struct {
	ID           pgtype.UUID        `json:"id"`
	FirstName    string             `json:"first_name"`
	LastName     string             `json:"last_name"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	DepartmentID pgtype.UUID        `json:"department_id"`
	Role         EmployeeRole       `json:"role"`
	Status       EmployeeStatus     `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
