// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type RecordStatus string

const (
	RecordStatusActive   RecordStatus = "active"
	RecordStatusInactive RecordStatus = "inactive"
)

func (e *RecordStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RecordStatus(s)
	case string:
		*e = RecordStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for RecordStatus: %T", src)
	}
	return nil
}

type NullRecordStatus struct {
	RecordStatus RecordStatus `json:"record_status"`
	Valid        bool         `json:"valid"` // Valid is true if RecordStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRecordStatus) Scan(value interface{}) error {
	if value == nil {
		ns.RecordStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RecordStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRecordStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RecordStatus), nil
}

type Department struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Code      string             `json:"code"`
	ParentID  pgtype.UUID        `json:"parent_id"`
	Status    RecordStatus       `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
