// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AssetCondition string

const (
	AssetConditionNew     AssetCondition = "new"
	AssetConditionGood    AssetCondition = "good"
	AssetConditionFair    AssetCondition = "fair"
	AssetConditionPoor    AssetCondition = "poor"
	AssetConditionDamaged AssetCondition = "damaged"
)

func (e *AssetCondition) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AssetCondition(s)
	case string:
		*e = AssetCondition(s)
	default:
		return fmt.Errorf("unsupported scan type for AssetCondition: %T", src)
	}
	return nil
}

type NullAssetCondition struct {
	AssetCondition AssetCondition `json:"asset_condition"`
	Valid          bool           `json:"valid"` // Valid is true if AssetCondition is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAssetCondition) Scan(value interface{}) error {
	if value == nil {
		ns.AssetCondition, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AssetCondition.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAssetCondition) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AssetCondition), nil
}

func (e AssetCondition) Valid() bool {
	switch e {
	case AssetConditionNew,
		AssetConditionGood,
		AssetConditionFair,
		AssetConditionPoor,
		AssetConditionDamaged:
		return true
	}
	return false
}

type AssetStatus string

const (
	AssetStatusAvailable        AssetStatus = "available"
	AssetStatusAssigned         AssetStatus = "assigned"
	AssetStatusUnderMaintenance AssetStatus = "under_maintenance"
	AssetStatusRetired          AssetStatus = "retired"
	AssetStatusLost             AssetStatus = "lost"
)

func (e *AssetStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AssetStatus(s)
	case string:
		*e = AssetStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AssetStatus: %T", src)
	}
	return nil
}

type NullAssetStatus struct {
	AssetStatus AssetStatus `json:"asset_status"`
	Valid       bool        `json:"valid"` // Valid is true if AssetStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAssetStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AssetStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AssetStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAssetStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AssetStatus), nil
}

func (e AssetStatus) Valid() bool {
	switch e {
	case AssetStatusAvailable,
		AssetStatusAssigned,
		AssetStatusUnderMaintenance,
		AssetStatusRetired,
		AssetStatusLost:
		return true
	}
	return false
}

type EmployeeStatus string

const (
	EmployeeStatusActive     EmployeeStatus = "active"
	EmployeeStatusInactive   EmployeeStatus = "inactive"
	EmployeeStatusOnLeave    EmployeeStatus = "on_leave"
	EmployeeStatusTerminated EmployeeStatus = "terminated"
)

func (e *EmployeeStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EmployeeStatus(s)
	case string:
		*e = EmployeeStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for EmployeeStatus: %T", src)
	}
	return nil
}

type NullEmployeeStatus struct {
	EmployeeStatus EmployeeStatus `json:"employee_status"`
	Valid          bool           `json:"valid"` // Valid is true if EmployeeStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEmployeeStatus) Scan(value interface{}) error {
	if value == nil {
		ns.EmployeeStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EmployeeStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEmployeeStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EmployeeStatus), nil
}

func (e EmployeeStatus) Valid() bool {
	switch e {
	case EmployeeStatusActive,
		EmployeeStatusInactive,
		EmployeeStatusOnLeave,
		EmployeeStatusTerminated:
		return true
	}
	return false
}

type UserRole string

const (
	UserRoleAdmin   UserRole = "admin"
	UserRoleManager UserRole = "manager"
	UserRoleViewer  UserRole = "viewer"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

func (e UserRole) Valid() bool {
	switch e {
	case UserRoleAdmin,
		UserRoleManager,
		UserRoleViewer:
		return true
	}
	return false
}

type Asset struct {
	ID           uuid.UUID          `json:"id"`
	Name         string             `json:"name"`
	AssetTag     string             `json:"asset_tag"`
	SerialNumber *string            `json:"serial_number"`
	CategoryID   pgtype.UUID        `json:"category_id"`
	DepartmentID pgtype.UUID        `json:"department_id"`
	AssignedTo   pgtype.UUID        `json:"assigned_to"`
	Status       AssetStatus        `json:"status"`
	Condition    AssetCondition     `json:"condition"`
	PurchaseDate pgtype.Date        `json:"purchase_date"`
	PurchaseCost pgtype.Numeric     `json:"purchase_cost"`
	Notes        *string            `json:"notes"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Category struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Department struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Employee struct {
	ID           uuid.UUID          `json:"id"`
	FirstName    string             `json:"first_name"`
	LastName     string             `json:"last_name"`
	Email        string             `json:"email"`
	Phone        *string            `json:"phone"`
	DepartmentID pgtype.UUID        `json:"department_id"`
	JobTitle     *string            `json:"job_title"`
	Status       EmployeeStatus     `json:"status"`
	HireDate     pgtype.Date        `json:"hire_date"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID           uuid.UUID          `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Role         UserRole           `json:"role"`
	EmployeeID   pgtype.UUID        `json:"employee_id"`
	IsActive     bool               `json:"is_active"`
	LastLoginAt  pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
