// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountEmployees(ctx context.Context) (int64, error)
	CountEmployeesByStatus(ctx context.Context, status EmployeeStatus) (int64, error)
	CreateEmployee(ctx context.Context, arg CreateEmployeeParams) (Employee, error)
	DeleteEmployee(ctx context.Context, id uuid.UUID) error
	GetEmployeeByEmail(ctx context.Context, email string) (Employee, error)
	GetEmployeeByID(ctx context.Context, id uuid.UUID) (Employee, error)
	ListEmployees(ctx context.Context) ([]Employee, error)
	ListEmployeesByDepartment(ctx context.Context, departmentID pgtype.UUID) ([]Employee, error)
	ListEmployeesByStatus(ctx context.Context, status EmployeeStatus) ([]Employee, error)
	UpdateEmployee(ctx context.Context, arg UpdateEmployeeParams) (Employee, error)
	UpdateEmployeeStatus(ctx context.Context, arg UpdateEmployeeStatusParams) (Employee, error)
}

var _ Querier = (*Queries)(nil)
