// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateDepartment(ctx context.Context, arg CreateDepartmentParams) (CreateDepartmentRow, error)
	DepartmentCodeExists(ctx context.Context, code string) (bool, error)
	DepartmentCodeExistsExcludingID(ctx context.Context, arg DepartmentCodeExistsExcludingIDParams) (bool, error)
	DepartmentNameExists(ctx context.Context, name string) (bool, error)
	DepartmentNameExistsExcludingID(ctx context.Context, arg DepartmentNameExistsExcludingIDParams) (bool, error)
	GetDepartmentByID(ctx context.Context, id pgtype.UUID) (GetDepartmentByIDRow, error)
	ListDepartments(ctx context.Context) ([]ListDepartmentsRow, error)
	ParentDepartmentExists(ctx context.Context, parentID pgtype.UUID) (bool, error)
	UpdateDepartment(ctx context.Context, arg UpdateDepartmentParams) (UpdateDepartmentRow, error)
	UpdateDepartmentStatus(ctx context.Context, arg UpdateDepartmentStatusParams) (UpdateDepartmentStatusRow, error)
}

var _ Querier = (*Queries)(nil)
